CREATE TABLE `projectmanagement_tasks` (
  `task_id` varchar(36) NOT NULL,
  `project_id` varchar(36) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` longtext DEFAULT NULL,
  `state` int(11) DEFAULT 0,
  `source_language` varchar(5) DEFAULT NULL,
  `target_language` varchar(5) DEFAULT NULL,
  `unit_text` varchar(255) DEFAULT NULL,
  `createdate` date NOT NULL,
  `updatedate` date NOT NULL,
  `article` varchar(255) DEFAULT NULL,
  `amount` decimal(15,5) DEFAULT NULL,
  `singleprice` decimal(15,5) DEFAULT NULL,
  `unit` int(11) DEFAULT NULL,
  `current_translator` varchar(10) DEFAULT NULL,
  `tr_offer_request` tinyint(4) DEFAULT 0,
  `tr_offer_value` decimal(15,5) DEFAULT 0.00000,
  `tr_offer_accepted` tinyint(4) DEFAULT 0,
  `tr_offer_rejected` tinyint(4) DEFAULT 0,
  `tr_request_accepted` tinyint(4) DEFAULT 0,
  `tr_request_rejected` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`task_id`),
  KEY `fk_projectmanagement_tasks_id` (`project_id`),
  KEY `fk_projectmanagement_tasks_state` (`state`),
  CONSTRAINT `fk_projectmanagement_tasks_id` FOREIGN KEY (`project_id`) REFERENCES `projectmanagement` (`project_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_projectmanagement_tasks_state` FOREIGN KEY (`state`) REFERENCES `projectmanagement_states` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) WITH SYSTEM VERSIONING